# Generated by Django 3.2.9 on 2021-11-30 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Imagen', models.CharField(max_length=100, null=True)),
                ('Descripcion', models.CharField(max_length=1000)),
                ('Valoracion', models.FloatField()),
                ('Year', models.IntegerField()),
                ('Terminado', models.BooleanField()),
                ('Last_Update', models.DateField()),
                ('Cantidad_Capitulos', models.IntegerField()),
                ('Categorias', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecomindApp.categorias')),
                ('Director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecomindApp.directores')),
                ('Tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecomindApp.tipos')),
            ],
        ),
        migrations.CreateModel(
            name='Categorias_Aplicadas',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecomindApp.categorias')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecomindApp.items')),
            ],
        ),
    ]
