# Generated by Django 3.2.9 on 2021-12-05 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecomindApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Desarrollador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecomindApp.desarrollador'),
        ),
        migrations.AddField(
            model_name='items',
            name='Estudio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecomindApp.estudio'),
        ),
    ]
