# Generated by Django 3.2.9 on 2021-12-11 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecomindApp', '0002_auto_20211205_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='Tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RecomindApp.tipos'),
        ),
    ]
